In [1]:
import pandas as pd
import numpy as np
import math as mt
import statistics as st
import matplotlib.pyplot as plt
import seaborn as sns
TwGames = pd.read_csv('Twitch_game_data.csv')
TwGames

,Game,Rank,Month,Year,Hours_watched,Hours_Streamed,Peak_viewers,Peak_channels,Streamers,Avg_viewers,Avg_channels,Avg_viewer_ratio
0,League of Legends,1,1,2016,94377226,1362044,530270,2903,129172,127021,1833,69.29
1,Counter-Strike: Global Offensive,2,1,2016,47832863,830105,372654,2197,120849,64378,1117,57.62
2,Dota 2,3,1,2016,45185893,433397,315083,1100,44074,60815,583,104.26
3,Hearthstone,4,1,2016,39936159,235903,131357,517,36170,53749,317,169.29
4,Call of Duty: Black Ops III,5,1,2016,16153057,1151578,71639,3620,214054,21740,1549,14.03
...,...,...,...,...,...,...,...,...,...,...,...,...
12345,Visage,196,12,2020,524013,18022,16424,78,3960,705,24,29.08
12346,Outlast,197,12,2020,519209,27662,97966,107,8728,698,37,18.77
12347,Call of the Sea,198,12,2020,515643,8380,45252,104,1806,694,11,61.53
12348,Fallout 76,199,12,2020,515422,79420,3226,201,6147,693,106,6.49
12349,Lineage: The Blood Pledge,200,12,2020,513380,12613,5460,24,43,690,16,40.70

In [2]:
TwGames.astype({"Avg_viewer_ratio":  int})

,Game,Rank,Month,Year,Hours_watched,Hours_Streamed,Peak_viewers,Peak_channels,Streamers,Avg_viewers,Avg_channels,Avg_viewer_ratio
0,League of Legends,1,1,2016,94377226,1362044,530270,2903,129172,127021,1833,69
1,Counter-Strike: Global Offensive,2,1,2016,47832863,830105,372654,2197,120849,64378,1117,57
2,Dota 2,3,1,2016,45185893,433397,315083,1100,44074,60815,583,104
3,Hearthstone,4,1,2016,39936159,235903,131357,517,36170,53749,317,169
4,Call of Duty: Black Ops III,5,1,2016,16153057,1151578,71639,3620,214054,21740,1549,14
...,...,...,...,...,...,...,...,...,...,...,...,...
12345,Visage,196,12,2020,524013,18022,16424,78,3960,705,24,29
12346,Outlast,197,12,2020,519209,27662,97966,107,8728,698,37,18
12347,Call of the Sea,198,12,2020,515643,8380,45252,104,1806,694,11,61
12348,Fallout 76,199,12,2020,515422,79420,3226,201,6147,693,106,6
12349,Lineage: The Blood Pledge,200,12,2020,513380,12613,5460,24,43,690,16,40

In [5]:
TwGames.isnull()

,Game,Rank,Month,Year,Hours_watched,Hours_Streamed,Peak_viewers,Peak_channels,Streamers,Avg_viewers,Avg_channels,Avg_viewer_ratio
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
12345,False,False,False,False,False,False,False,False,False,False,False,False
12346,False,False,False,False,False,False,False,False,False,False,False,False
12347,False,False,False,False,False,False,False,False,False,False,False,False
12348,False,False,False,False,False,False,False,False,False,False,False,False
12349,False,False,False,False,False,False,False,False,False,False,False,False